export const GET_COUNTRIES = 'GET_COUNTRIES';

export const FILTER_COUNTRIES = 'FILTER_COUNTRIES';

export const ORDER_COUNTRIES_ALF = 'ORDER_COUNTRIES_ALF';

export const ORDER_COUNTRIES_POP = 'ORDER_COUNTRIES_POP';

export const GET_COUNTRY_DETAIL = 'GET_COUNTRY_DETAIL';

export const ADD_TOURIST_ACTIVITIES = 'ADD_ACTIVITIES'; 

export const GET_TOURIST_ACTIVITIES = 'GET_ACTIVITIES';

export const GET_COUNTRIES_QUERY = 'GET_COUNTRIES_QUERY';

export const FILTER_BY_ACTIVITIES = 'FILTER_BY_ACTIVITIES';